### ISSUE TITLE
Intermittent DomainEventDispatcherTests test failure

### ISSUE THREAD

**Issue by rabuckley** [dseinternational/open-dotnet#192]
```
Assert.True() Failure
  Expected: True
  Actual:   False
    at DSE.Open.DomainModel.Tests.Events.DomainEventDispatcherTests.Dispatcher_PublishEvents() in /home/runner/work/open-dotnet/open-dotnet/test/DSE.Open.DomainModel.Tests/Events/DomainEventDispatcherTests.cs:62
```

https://github.com/dseinternational/open-dotnet/blob/c2b6c7b773c210ddf99725b12d11505719ff4fcf/test/DSE.Open.DomainModel.Tests/Events/DomainEventDispatcherTests.cs#L37-L62

Failing assert is

```cs
Assert.True(state.ContainsKey(bev.Instance.ToString())); 
```

**Comment by rabuckley** [comment]
Perhaps, but that won't fix it. Looks like a race between the background event being added to `state` and us reading state to see if the event is in there.

**Comment by rabuckley** [comment]
```
failed DSE.Open.DomainModel.Tests.Events.DomainEventDispatcherTests.Dispatcher PublishEvents (76ms)
  Xunit.Runner.InProc.SystemConsole.TestingPlatform.XunitException: System.InvalidOperationException : Error invoking DomainEventHandlerFake handler for DomainEventFake message.
  ---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  -------- System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
    at CommunityToolkit.Diagnostics.ThrowHelper.ThrowInvalidOperationException(String message, Exception innerException)
    at DSE.Open.Mediators.MessageDispatcher.<>c__DisplayClass3_1.<PublishAsync>b__0() in /_/src/DSE.Open.Mediators/MessageDispatcher.cs:77
    at System.Threading.Tasks.Task`1.InnerInvoke()
    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location ---
    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
    --- End of stack trace from previous location ---
    at DSE.Open.Mediators.MessageDispatcher.PublishAsync(IMessage message, CancellationToken cancellationToken) in /_/src/DSE.Open.Mediators/MessageDispatcher.cs:56
    at DSE.Open.DomainModel.Events.DomainEventDispatcher.PublishEventsAsync(IEnumerable`1 entities, CancellationToken cancellationToken) in /_/src/DSE.Open.DomainModel/Events/DomainEventDispatcher.cs:87
    at DSE.Open.DomainModel.Tests.Events.DomainEventDispatcherTests.Dispatcher_PublishEvents() in /home/runner/work/open-dotnet/open-dotnet/test/DSE.Open.DomainModel.Tests/Events/DomainEventDispatcherTests.cs:57
    --- End of stack trace from previous location ---
    ----- Inner Stack Trace -----
    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
    at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
    at System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args, CultureInfo culture)
    at DSE.Open.Mediators.MessageDispatcher.<>c__DisplayClass3_1.<PublishAsync>b__0() in /_/src/DSE.Open.Mediators/MessageDispatcher.cs:62
    ----- Inner Stack Trace -----
    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
    at DSE.Open.DomainModel.Tests.Events.DomainEventHandlerFake.HandleAsync(DomainEventFake message, CancellationToken cancellationToken) in /home/runner/work/open-dotnet/open-dotnet/test/DSE.Open.DomainModel.Tests/Events/DomainEventHandlerFake.cs:19
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```
